version: 1.0.0

# possible values are CRITICAL, ERROR, WARNING, INFO, DEBUG
log_level: "INFO"

# settings for the timer implementation
timer:
  # maximum time to stay in cpu bound loop (i.e. a while loop that does nothing)
  max_cpu_buffer: 0.0 # seconds
  # the period expected for every iteration
  loop_time: 0.02 # seconds

# encoder configuration section
encoder:
  # set a path to your custom preprocessor plugin
  # preprocessor: 'plugins/preprocessor.py'

  model: "plugins/model.py"

  # set a path to your custom postprocessor plugin
  postprocessor: "plugins/postprocessor.py"

  input:
    # possible values are "LSL" or "file"
    type: "LSL"
    # LSL settings if the input type is "LSL"
    lsl:
      stream_name: "NDS-Behavior"
      # maximum time for attempting a connection to an LSL input stream
      connection_timeout: 60.0 # seconds
    # file settings if the input type is "file"
    file:
      # paths can be absolute or relative to the current work directory
      path: "sample_data/session_4_behavior_standardized.npz"
      sampling_rate: 50 # Hz
      timestamps_array_name: "timestamps_train"
      data_array_name: "vel_train"

  output:
    n_channels: 190
    # possible values are "LSL" or "file"
    type: "LSL"
    # LSL settings if the output type is "LSL"
    lsl:
      # possible values are "float32", "double64", "int8", "int16", "int32", "int64"
      channel_format: "int16"
      stream_name: "NDS-SpikeRates"
      stream_type: "SpikingRates"
      source_id: "SimulatedSpikeRates"
      instrument:
        manufacturer: "Blackrock Neurotech"
        model: "Simulated"
        id: 0
    # file path if the output type is a file
    file: "output.csv"

# ephys_generator configuration section
ephys_generator:
  # uncomment the configuration below to fix the random seed used to generate spikes
  # random_seed: 12332323

  input:
    # possible values are "LSL", "testing"
    type: "LSL"
    # LSL settings if the input type is "LSL"
    lsl:
      stream_name: "NDS-SpikeRates"
      # maximum time for attempting a connection to an LSL input stream
      connection_timeout: 60.0 # seconds
    # settings if the input type is "test"
    testing:
      # number of channels for the "testing" input type
      n_channels: 50

  output:
    raw:
      lsl:
        # possible values are "float32", "double64", "int8", "int16", "int32", "int64"
        channel_format: "int16"
        stream_name: "NDS-RawData"
        stream_type: "Ephys"
        source_id: "SimulatedRawData"
        instrument:
          manufacturer: "Blackrock Neurotech"
          model: "Simulated"
          id: 0
    lfp:
      data_frequency: 1_000 # Hz
      filter_cutoff: 300 # Hz
      filter_order: 4 # number
      lsl:
        # possible values are "float32", "double64", "int8", "int16", "int32", "int64"
        channel_format: "int16"
        stream_name: "NDS-LFPData"
        stream_type: "LFP"
        source_id: "SimulatedLFPData"
        instrument:
          manufacturer: "Blackrock Neurotech"
          model: "Simulated"
          id: 0
    spike_events:
      lsl:
        # possible values are "float32", "double64", "int8", "int16", "int32", "int64"
        channel_format: "int16"
        stream_name: "NDS-SpikeEvents"
        stream_type: "SpikeEvents"
        source_id: "SimulatedSpikeEvents"
        instrument:
          manufacturer: "Blackrock Neurotech"
          model: "Simulated"
          id: 0

  # Gaussian (1/f)**beta noise settings
  noise:
    # exponent
    beta: 1.5
    # noise standard deviation
    standard_deviation: 40.0
    # low-frequency cutoff. The power-spectrum below fmin is flat.
    fmin: 0.0001
    # unique noise samples to generate per channel
    samples: 262144

  resolution: 0.25 # uV per count

  waveforms:
    n_samples: 48 # number
    prototypes:
      # prototype_id: uV
      1: "[0.0, 8.5, 17.0, 24.0, 30.75, 47.75, 64.5, 72.75, 81.25, 72.75, 64.5, 28.0, -8.25, -99.25, -190.0, -194.25, -198.5, -172.0, -145.25, -95.0, -44.75, 1.5, 47.75, 68.75, 89.5, 92.5, 95.25, 82.5, 70.0, 57.5, 44.75, 29.5, 14.0, 7.0, 0.0, -2.75, -5.5, -7.0, -8.25, -4.0, 0.0]"
      2: "[0.0, -4.0, -8.25, -16.75, -25.0, -74.0, -123.0, -111.75, -100.5, 8.5, 117.5, 137.25, 156.75, 117.5, 78.5, 22.5, -33.5, -41.75, -50.25, -47.5, -44.75, -40.5, -36.25, -25.0, -14.0, -5.5, 3.0, 10.0, 17.0, 18.25, 19.75, 11.25, 3.0, -1.25, -5.5, -5.5, -5.5, -4.0, -2.75, -1.25, 0.0]"
      3: "[0.0, -5.5, -11.0, -25.0, -39.0, -95.0, -151.0, -151.0, -151.0, -99.25, -47.5, 8.5, 64.5, 106.5, 148.25, 175.0, 201.5, 169.25, 137.25, 89.5, 42.0, 22.5, 3.0, -5.5, -14.0, -16.75, -19.5, -21.0, -22.25, -22.25, -22.25, -22.25, -22.25, -21.0, -19.5, -15.25, -11.0, -9.75, -8.25, -4.0, 0.0]"

    unit_prototype_mapping:
      default: 1 # by default every unit outputs prototype 1 waveform
      # 1: 3 # second unit (unit 1) uses prototype 3

  raw_data_frequency: 30_000 # Hz
  n_units_per_channel: 1 # number of distinct waveforms in each channel

  refractory_time: 0.001 # seconds

  lsl_chunk_frequency: 1_000 # Hz
