# Publish the python package when project is tagged in the v*.*.* form
name: Python package
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and publish to pypi
        uses: JRubics/poetry-publish@v1.16
        with:
          pypi_token: ${{ secrets.TEST_PYPI_TOKEN }}
          # following 2 lines set deployment to testpypi
          repository_name: "testpypi"
          repository_url: "https://test.pypi.org/legacy/" 
